name: Create Pull Request
on:
  workflow_call:
    secrets:
      github-token:
        description: secrets.BUILD_GITHUB_TOKEN
        required: true

defaults:
  run:
    shell: pwsh

jobs:
  create:
    name: Create
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate
        run: echo "${{ secrets.github-token }}" | gh auth login --with-token

      - name: Check for Existing PR
        id: check
        run: |
          $count = (ConvertFrom-Json($(gh pr list -R "${{ github.repository }}" -S "base:main head:risk" --json number))).Count
          if ($count -eq 0) {
            echo "create=true" >> $env:GITHUB_OUTPUT
          }

      - uses: actions/checkout@v3
        if: ${{ steps.check.outputs.create }}

      - name: Create PR
        if: ${{ steps.check.outputs.create }}
        run: gh pr create -R "${{ github.repository }}" --title "Merge branch 'risk' into 'main'" --body "risk -> main" --base "main" --head "risk"
