name: Initiate Automated Deployments
on:
  workflow_call:
    inputs:
      disable-demo-environment:
        description: Disable the demo deployment environment
        required: false
        type: boolean
        default: false
      disable-qa-environment:
        description: Disable the QA deployment environment
        required: false
        type: boolean
        default: false
    secrets:
      github-token:
        description: secrets.BUILD_GITHUB_TOKEN
        required: true

defaults:
  run:
    shell: pwsh

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.environments.outputs.environments }}
    steps:
      - name: Determine Environments
        id: environments
        run: |
          $branch = "${{ github.event.workflow_run.head_branch }}"
          $disableDemoEnvironment = [System.Boolean]::Parse("${{ inputs.disable-demo-environment }}")
          $disableQaEnvironment = [System.Boolean]::Parse("${{ inputs.disable-qa-environment }}")
          
          switch ($branch) {
            "dev" { $environments = @("dev") }
            "main" {
              if ($disableDemoEnvironment -eq $true) {
                $environments = @("production")
              }
              else {
                $environments = @("production", "demo")
              }
            }
            "regression" { $environments = @("risk") }
            "risk" {
              if ($disableQaEnvironment -eq $true) {
                $environments = @("risk")
              }
              else {
                $environments = @("risk", "qa")
              }
            }
            default { $environments = @($branch) }
          }

          echo "environments=$(ConvertTo-Json -Compress $environments)" >> $env:GITHUB_OUTPUT

  invoke-deployment-workflow:
    name: Invoke Deployment
    runs-on: ubuntu-latest
    needs: [init]
    strategy:
      matrix:
        environment: ${{ fromJSON(needs.init.outputs.environments) }}
    steps:
      - name: Authenticate
        run: echo "${{ secrets.github-token }}" | gh auth login --with-token

      - name: Invoke Deployment Workflow
        run: gh workflow run deploy.yml --ref ${{ github.event.workflow_run.head_branch }} -f "environment=${{ matrix.environment }}" -R ${{ github.repository }}
